Add Trustworthy Systems seL4 projects to roadmap
seL4/docs pull request #200
Opened 2023-09-14 10:40 UTC by Ivan-Velickovic

2023-09-15 13:36 UTC, lsf37 approved these changes
Looks good from my side. @gernotheiser are you happy with those?

2023-09-15 22:56 UTC, gernotheiser requested changes
> status: "Ongoing. To be released at the end of 2023."

This is going to be a prototype release, proper release will be in March

Also, I wonder whether we should indicate that this will be the first part of Lions OS?

2023-09-17 22:02 UTC, Ivan-Velickovic commented
> This is going to be a prototype release, proper release will be in March

I've mentioned that now.

> Also, I wonder whether we should indicate that this will be the first part of Lions OS?

There doesn't seem to be any page on the TS website that mentions Lions OS yet, so I don't think the majority of people would know what we're referring to. Can add a mention/link to Lions OS if/when there is more concrete information about it.

2023-09-17 22:08 UTC, gernotheiser approved these changes

2023-09-19 19:39 UTC, merged